moe/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path('^$', views.KirokuView.as_view(), name='kiroku_list'),
    re_path('x/$', views.AjaxWriteView.as_view(), name='ajax_write'),
]

moesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moe/', include('moe.urls')),
]

moe/models.py
from django.db import models
from django.utils import timezone

class Kiroku(models.Model):
    dt = models.DateTimeField(default=timezone.now)
    moyori_cnt = models.IntegerField()
    moe_cnt = models.IntegerField()

    # def __str__(self):
    #     return self.cnt

class Mokuhyo(models.Model):
    last_moyori = models.IntegerField()
    last_moe = models.IntegerField()

moe/forms.py
from django import forms


class GreetForm(forms.Form):
    dt = forms.CharField(label='日時')
    moyori_cnt = forms.CharField(label='最寄り駅回数')
    moe_cnt = forms.CharField(label='もえ仕事回数')

moe/views.py
import datetime
import math
from django.shortcuts import render
from django.views import generic
from django.http import JsonResponse
from django.utils.timezone import make_aware
from django.db.models import Avg, Min, Max
from . import models

# Create your views here.

class KirokuView(generic.ListView):
    # login_url = '/app/login/'
    template_name = 'moe/kiroku_list.html'
    models = models.Kiroku
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        kiroku = models.Kiroku.objects.all().order_by('dt')
        old_moyori = 0
        old_moe = 0
        out = []
        for i in kiroku:
            diff_moyori = 0 if old_moyori == 0 else int(i.moyori_cnt) - old_moyori
            diff_moe = 0 if old_moe == 0 else int(i.moe_cnt) - old_moe
            old_moyori = i.moyori_cnt
            old_moe = i.moe_cnt
            out.append({
                "dt": i.dt,
                "moyori_cnt": int(i.moyori_cnt),
                "moe_cnt": int(i.moe_cnt),
                "diff_moyori": diff_moyori,
                "diff_moe": diff_moe,
            })
        context['datas'] = out

        # 過去７日間
        kako7 = datetime.datetime.now() - datetime.timedelta(days=7)
        # kiroku_ave = models.Kiroku.objects.filter(dt__gt=make_aware(kako7)).aggregate(ave_moyori_cnt=Avg('moyori_cnt'), ave_moe_cnt=Avg('moe_cnt'))
        kiroku2 = models.Kiroku.objects.filter(dt__gt=make_aware(kako7)).aggregate(
            min_moyori_cnt=Min('moyori_cnt'), 
            max_moyori_cnt=Max('moyori_cnt'), 
            min_moe_cnt=Min('moe_cnt'),
            max_moe_cnt=Max('moe_cnt'),
            max_dt=Max('dt'),
            min_dt=Min('dt')
            )
        diff_moyori = kiroku2['max_moyori_cnt'] - kiroku2['min_moyori_cnt']
        diff_moe = kiroku2['max_moe_cnt'] - kiroku2['min_moe_cnt']
        diff_dt = kiroku2['max_dt'] - kiroku2['min_dt']
        ave_moyori = diff_moyori / diff_dt.days
        ave_moe = diff_moe / diff_dt.days
        left_day_moyori = math.ceil((50000 - kiroku2['max_moyori_cnt']) / ave_moyori)
        left_day_moe3 = math.ceil((30000 - kiroku2['max_moe_cnt']) / ave_moe)
        left_day_moe5 = math.ceil((50000 - kiroku2['max_moe_cnt']) / ave_moe)
        reach_moyori = make_aware(datetime.datetime.now() + datetime.timedelta(days=left_day_moyori))
        reach_moe3 = make_aware(datetime.datetime.now() + datetime.timedelta(days=left_day_moe3))
        reach_moe5 = make_aware(datetime.datetime.now() + datetime.timedelta(days=left_day_moe5))
        context['otherdata'] = {
            "left_day_moyori": left_day_moyori,
            "left_day_moe3": left_day_moe3,
            "left_day_moe5": left_day_moe5,
            "ave_moyori": math.floor(ave_moyori),
            "ave_moe": math.floor(ave_moe),
            "reach_moyori": reach_moyori,
            "reach_moe3": reach_moe3,
            "reach_moe5": reach_moe5,
        }

        return context

    def get_queryset(self):
        return models.Kiroku.objects.all().order_by('-dt')  


class AjaxWriteView(generic.FormView):
    def post(self, request, *args, **kwargs):
        print(request.POST)
        """ save data """
        input_dt = request.POST.get("dt", "").replace("-", "/")
        if input_dt != "":
            dt = datetime.datetime.strptime(input_dt, '%Y/%m/%d %H:%M')
        else:
            dt = datetime.datetime.now()
        dt_aware = make_aware(dt)
        kiroku_obj = models.Kiroku(
            dt=dt_aware,
            moyori_cnt=request.POST.get('moyori').replace(",", ""),
            moe_cnt=request.POST.get('moe').replace(",", ""))
        kiroku_obj.save()

        return JsonResponse({
            "stat": "OK",
            "dt": dt_aware
            })

moesite/templates/moe/base.html
{% load static %}
<!DOCTYPE html>
<html class=" " lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>I love Moe</title>
    <!-- Bootstrap -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static "custom.css" %}" rel="stylesheet">
    <link href="{% static "z_add.css" %}" rel="stylesheet">
    <link href="/static/bootstrap_datepicker_plus/css/datepicker-widget.css" type="text/css" media="all" rel="stylesheet">
    <style>
      .table {
        margin-bottom: 2px;
      }
    </style>
    {% block anothercss %}
    {% endblock %}
  </head>
  <body class="nav-md">
    
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/app/" class="site_title"><i class="fa fa-coffee"></i> <span>回数管理</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <!-- <img src="{% static "img.jpg" %}" alt="..." class="img-circle profile_img"> -->
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ user_data.full_name }} </h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br>

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section active">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li class="active"><a><i class="fa fa-edit"></i> メインメニュー <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: block;">
                      <li><a href="/app/kiroku/"><i class="fa fa-file-text-o" aria-hidden="true"></i>記録一覧</a></li>
                      <li><a href="/app/logout/"><i class="fa fa-sign-out" aria-hidden="true"></i>ログアウト</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <!-- /menu footer buttons -->
          </div>
        </div>


        <!-- page content -->
        <div class="right_col" role="main" style="min-height: 800px;">
          <div class="">
            <div class="xpage-title " style="height: 32px;">
              {% block pagetitle %}
              {% endblock %}
              <!-- <div class="title_left">
                <h3>Form Elements</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div> -->
            </div>

            <div class="clearfix">
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            &copy; 2021 djanzu
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>    <!-- Custom Theme Scripts -->
    <!-- Bootstrap -->
    <script src="{% static "bootstrap.js" %}" type="text/javascript"></script>
    <script src="{% static "custom.js" %}" type="text/javascript"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap_datepicker_plus/js/datepicker-widget.js"></script> 


<tester style="position: absolute; top: -9999px; left: -9999px; width: auto; font-size: 13px; font-family: helvetica; font-weight: 400; letter-spacing: 0px; white-space: nowrap;" id="tags_1_tag_autosize_tester"></tester>

{% block anotherJS %}
{% endblock %}

</body>
</html>

moesite/templates/moe/kiroku_list.html
{% extends "moe/base.html" %}
{% load humanize %}

{% block pagetitle %}
<h2>記録一覧</h2>
{% endblock %}

{% block content %}
<table class="table table-striped table-responsive">
<thead>
  <tr>
    <th>日時</th>
    <th>最寄り駅</th>
    <th>差分</th>
    <th>もえ</th>
    <th>差分</th>
  </tr>
</thead>
<tbody>
  {% for item in datas %}
    <tr style="vertical-align: middle;">
      <td>{{ item.dt | date:"Y/m/d H:i:s" }}</td>
      <td>{{ item.moyori_cnt | intcomma }}</td>
      <td>{{ item.diff_moyori }}</td>
      <td>{{ item.moe_cnt | intcomma }}</td>
      <td>{{ item.diff_moe }}</td>
    </tr>
  {% endfor %}
  <!-- <tr>
    <td></td>
    <td>50,000 まであと{{ otherdata.left_day_moyori | intcomma }} 日</td>
    <td>{{ otherdata.ave_moyori }}</td>
    <td>
      30,000 まであと{{ otherdata.left_day_moe3 | intcomma }} 日({{ otherdata.reach_moyori }})<br>
      50,000 まであと{{ otherdata.left_day_moe5 | intcomma }} 日({{ otherdata.reach_moe3 }})
    </td>
    <td>{{ otherdata.ave_moe }}</td>
  </tr> -->
  <tr>
    <td><input type="text" id="id_dt" placeholder="2020/01/01 00:00:00"></td>
    <td><input type="text" id="id_moyori"></td>
    <td></td>
    <td><input type="text" id="id_moe"></td>
    <td><input type="button" id="id_submit" value="送 信"></td>
  </tr>
</tbody>
</table>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>最寄り駅 50,000</th>
      <td>あと{{ otherdata.left_day_moyori | intcomma }} 日({{ otherdata.reach_moyori | date:"Y/m/d" }})</td>
      <td>平均 {{ otherdata.ave_moyori }} 回</td>
    </tr>
    <tr>
      <th>もえ 30,000</th>
      <td>
        あと{{ otherdata.left_day_moe3 | intcomma }} 日({{ otherdata.reach_moe3 | date:"Y/m/d" }})
      </td>
      <td>平均 {{ otherdata.ave_moe }} 回</td>
    </tr>
    <tr>
      <th>もえ 50,000</th>
      <td>
        あと{{ otherdata.left_day_moe5 | intcomma }} 日({{ otherdata.reach_moe5 | date:"Y/m/d"}})
      </td>
      <td></td>
    </tr>
  </thead>
</table>
  
{% csrf_token %}
{% endblock %}

{% block anotherJS %}
<script>
  $(function(){
    $("#id_submit").click(function(e){
      $.ajax({
        url: "/moe/x/",
        method: "POST",
        dataType: "text",
        data: {
          dt: $("#id_dt").val(),
          moyori: $("#id_moyori").val(),
          moe: $("#id_moe").val(),
          csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
        },
        timeout: 5000,
      }).done(function(r){
        console.log(r);
        location.reload();
      });
    });
  });
</script>
{% endblock %}